# dmgbuild settings for Greeting Cards installer.
#
# `defines` is a dict injected by dmgbuild at runtime from -D CLI flags.
# F821 (undefined name) is suppressed for this file via pyproject.toml.
# pyright also excludes this file.
#
# Invoke via the orchestrator: uv run python -m scripts.dmg

# noinspection PyUnresolvedReferences
application = defines.get("app_path", "dist/Greeting Cards.app")
appname = "Greeting Cards"

# Files and symlinks to place in the DMG.
# App is added last so Finder doesn't pre-select an auxiliary item on open.
# noinspection PyUnresolvedReferences
_readme = defines.get("readme_path")
# noinspection PyUnresolvedReferences
_sample_cards = defines.get("sample_cards_path")

files = []
if _readme:
    files.append(_readme)
if _sample_cards:
    files.append(_sample_cards)
files.append(application)

symlinks = {"Applications": "/Applications"}

# Volume icon: badge the DMG with the app icon
badge_icon = application + "/Contents/Resources/icon.icns"

# Background: custom gradient image generated by scripts/dmg/background.py
# noinspection PyUnresolvedReferences
background = defines.get("background")

# Disk image format: UDBZ = bzip2, best compression
# noinspection PyShadowingBuiltins,PyUnresolvedReferences
format = defines.get("format", "UDBZ")
size = None  # auto-compute from contents

# Window chrome
show_status_bar = False
show_tab_view = False
show_toolbar = False
show_pathbar = False
show_sidebar = False
sidebar_width = 180

# Window position and size (logical points, not Retina pixels)
window_rect = ((200, 200), (660, 480))

# Icon view settings
default_view = "icon-view"
show_icon_preview = True
icon_size = 80
text_size = 13

# Icon positions (logical points within the 660×480 window).
# Positions determined by manual Finder placement on an editable DMG.
icon_locations = {
    "Greeting Cards.app": (152, 105),
    "Applications": (482, 105),
    "Read Me.rtfd": (152, 285),
    "Sample Cards": (482, 285),
}
