# Colors
BG_PRIMARY = "#FFFFFF"
BG_SECONDARY = "#F5F5F7"
BG_HOVER = "#E8E8ED"
BG_SELECTED = "#D4E4F7"
TEXT_PRIMARY = "#1D1D1F"
TEXT_SECONDARY = "#6E6E73"
ACCENT = "#007AFF"
SUCCESS = "#34C759"
WARNING = "#FF9500"
ERROR = "#FF3B30"

# Confidence dot colors
CONFIDENCE_COLORS = {
    "high": SUCCESS,
    "medium": WARNING,
    "low": ERROR,
    "none": TEXT_SECONDARY,
}

# Fonts
FONT_FAMILY = "Helvetica Neue"
FONT_TITLE = (FONT_FAMILY, 16, "bold")
FONT_HEADING = (FONT_FAMILY, 13, "bold")
FONT_BODY = (FONT_FAMILY, 12)
FONT_SMALL = (FONT_FAMILY, 11)
FONT_MONO = ("Menlo", 11)

# Dimensions
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 750
PREVIEW_WIDTH = 450
ROW_HEIGHT = 36
TOOLBAR_HEIGHT = 50
PAD = 10
