"""Before/after test data for reformat_md_tables end-to-end tests.

Generated by diffing files before and after PyCharm's "Reformat File" action.
Source files: docs/code-quality-audit.md, coverage-analysis.md
"""

QUALITY_AUDIT_BEFORE = """\
# Code Quality Audit

When asked to audit the codebase, follow this methodology. The audit uses a batch pre-pass for automated tools, then parallel agents in convergence passes to systematically review every file.

## What to Look For

Check for these categories across all files in `app/`, `tests/`, and `scripts/`.

### Categories

| Code | Category                      | Description                                                                                                                                                                                           |
|------|-------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| MT   | Missing tests                 | Public methods/functions without tests, untested error paths, shallow happy-path-only coverage                                                                                                        |
| UC   | Unused code                   | Dead imports, unreachable code paths, unused functions/variables                                                                                                                                      |
| TA   | Type annotations              | Functions missing `-> None` or return types, untyped parameters                                                                                                                                       |
| RC   | Repeated code                 | Duplicate logic across files that should be extracted to shared helpers                                                                                                                               |
| UP   | Unpythonic patterns           | `dict.__init__(self)` instead of `super().__init__()`, `lambda: Path()` instead of `Path`, `count == 0` instead of `not count`, etc.                                                                 |
| MC   | Magic constants               | Hardcoded strings, pixel values, colors, or numbers that should be named constants                                                                                                                    |
| HC   | Hardcoded colors              | `wx.Colour(...)` literals that duplicate values in `app/gui/styles.py`                                                                                                                                |
| PL   | Print instead of logging      | `print()` calls that should use `logging.getLogger(__name__)`                                                                                                                                         |
| IL   | Incomplete logic              | Missing else branches, unhandled empty/None cases, no input validation                                                                                                                                |
| BL   | Bugs and logic errors         | Race conditions, off-by-one errors, unbounded loops, case-sensitivity mismatches, stale state after mutations, silent exception swallowing that hides real failures                                    |
| SM   | Stale Makefile                | Targets referencing outdated paths, wrong Python versions, missing new entry points, or commands that no longer match the project structure                                                            |
| LR   | License registry gaps         | Run `make licenses-sync`, then check `content/licenses/registry.toml` for: missing license text files, empty homepage URLs, "Unknown" license types, platform-specific packages for the exclude list  |
| RL   | Redundant license config      | `content/licenses/config.toml` `[[package]]` entries that only exist when they override auto-discovered values. Remove entries where `display` matches `name` and no other fields are set             |

### Severity Key

- **HIGH (H)** — Bugs, logic errors, race conditions, security issues — things that cause incorrect behavior
- **MEDIUM (M)** — Structural issues with contained scope — repeated code, incomplete logic, missing validation
- **LOW (L)** — Minor issues, style concerns, small gaps — magic constants, missing annotations, unpythonic patterns
- **STYLE (S)** — Informational only, not actionable defects

## Static Analysis

Run the full static analysis suite and verify zero issues across all tools:

```bash
make check   # runs all of the below in sequence
```

| Tool        | Command                                                   | Scope                                                 | Expected             |
|-------------|-----------------------------------------------------------|-------------------------------------------------------|----------------------|
| pyright     | `pyright app/ scripts/ main.py`                           | Type checking (structural)                            | 0 errors, 0 warnings |
| mypy        | `uv run mypy app/ scripts/ main.py`                       | Type checking (nominal, SQLAlchemy plugin)            | 0 errors             |
| ruff check  | `uv run ruff check app/ scripts/ tests/ main.py`          | Linting (pyflakes, pycodestyle, isort, bugbear, etc.) | 0 errors             |
| ruff format | `uv run ruff format --check app/ scripts/ tests/ main.py` | Formatting                                            | 0 reformatted        |
| bandit      | `uv run bandit -r app/ scripts/ -c pyproject.toml`        | Security scan                                         | 0 issues             |

For each diagnostic, determine whether to:
- **Fix the code** — if the checker found a real bug or a type that should be tightened
- **Add a suppression comment** (`# type: ignore[code]` or `# pyright: ignore[code]`) — if the diagnostic is a false positive or an intentional pattern (e.g. `sys._MEIPASS`, wxPython stubs)

**Before applying any suppression comments**, summarize every suppression to the user with:
1. The file, line, and diagnostic code
2. What the checker is complaining about
3. Why suppression (rather than a fix) is the right call

Wait for user approval before adding suppressions. The user may decide to fix the code, file an upstream bug, or handle it differently.

## PyCharm Inspections

Always attempt to run PyCharm inspections on all Python files in `main.py`, `app/**/*.py`, and `scripts/*.py` via the JetBrains MCP server. See the "PyCharm Inspections (MCP)" section in `CLAUDE.md` for details.

If the MCP server is unavailable (PyCharm not running, plugin not installed, tool calls fail), note the reason in the audit report and continue — do not fail the overall audit.

## Methodology: Multi-Pass Convergence

The audit runs in iterative passes. A batch pre-pass captures automated tool output, then parallel agents review the codebase from different angles. Passes continue until a pass produces zero new findings (**convergence**).

### Pre-Pass — Automated Baseline (batch, not agents)

Run these and capture output as reference material for agent passes:

1. `make check` — all static analysis diagnostics
2. PyCharm inspections — via JetBrains MCP on all Python files
3. `uv run pytest tests/ -x` — test results and coverage
4. `make licenses-sync` — license registry state

Tool-reported issues become pre-pass findings (category TA, UC, etc.) in the findings table. Agents in subsequent passes should not re-report what tools already caught.

### Pass 1 — Broad Sweep (4 parallel general-purpose agents)

| Agent | Scope                                        | Focus                                                         |
|-------|----------------------------------------------|---------------------------------------------------------------|
| A     | `app/core/**/*.py`                           | All 13 categories within core modules                         |
| B     | `app/gui/**/*.py`                            | All 13 categories within GUI modules                          |
| C     | `app/models/*.py`, `scripts/*.py`, `main.py` | All 13 categories within models, scripts, entry point         |
| D     | `tests/**/*.py`                              | Coverage gaps (compare test files against source modules), MT  |

Each agent reads every file in its scope, checking:
1. **Import statements** — unused imports, circular dependencies
2. **Method bodies** — bugs, logic errors, race conditions, incomplete logic
3. **Type signatures** — missing annotations, loose types
4. **Constants and literals** — magic values, hardcoded colors
5. **Patterns** — unpythonic idioms, repeated code within scope
6. **Test coverage** — (Agent D) map source modules to test files, identify gaps

Each agent returns findings as a table with temporary IDs (A1, B1, C1, D1, ...).

### Interphase Consolidation Rules

After each pass:
1. **Deduplicate** — merge findings that describe the same issue from different agents
2. **Cross-reference pre-pass** — drop findings already reported by automated tools
3. **Adjust severity** — if a finding is confirmed with new context, upgrade or downgrade
4. **Strike rejected findings** — mark with ~~strikethrough~~ and note the rejection reason
5. **Assign final IDs** — sequential within severity (H1, M1, L1, S1)
6. **Update pass log** — record agent count, new findings, adjustments

### Pass 2 — Deep Dive + Validation (2–3 parallel agents)

| Agent | Focus                                                                                                                          |
|-------|--------------------------------------------------------------------------------------------------------------------------------|
| E     | **Cross-cutting**: repeated code across areas, inter-module coupling, shared pattern violations. Validates/rejects A, B, C.    |
| F     | **Bugs + logic**: trace error flows, race conditions, edge cases adjacent to Pass 1 hits. Validates/rejects BL/IL findings.    |
| G     | **Test coverage** (if D found gaps): map untested paths discovered by E and F. Validates/rejects D's findings. Optional.       |

Pass 2 agents receive the Pass 1 findings list. For each, they state **CONFIRMED** or **REJECTED** with reasoning. They also look for new findings in areas adjacent to Pass 1 hits.

### Pass 3+ — Convergence (1 agent)

One agent sweeps areas not specifically covered or lightly touched in prior passes:
- Makefile targets and project configuration (SM)
- License registry and config (LR, RL)
- Infrastructure files not in agent scopes
- Inter-module patterns missed by area-scoped agents
- Dead code across module boundaries

If this pass finds zero new findings, the audit is **converged**. Otherwise, repeat with targeted agents until convergence.

## Output

All findings go into `_build/audit/YYYYMMDDThhmm-code-quality.md` (timestamp of when the audit started). After convergence, group related findings into **clusters** — sets of findings that share a root cause or would be fixed together.

### Presentation Guidelines

- **HIGH and MEDIUM findings**: List individually in full detail tables (one row per finding). These are significant enough to warrant individual attention.
- **LOW findings**: Group by theme in a summary table. Each row is a theme (e.g., "Magic constants in GUI", "Missing type annotations in scripts") with a count and representative examples — not one row per finding.
- **STYLE findings**: Group by theme, same as LOW.
- **Missing Tests**: Separate table listing coverage gaps.
- **Clusters**: Present as a single table, not prose sections. Each row is a cluster with columns for name, included findings, root cause, fix approach, and priority.
- **Assessment**: After findings and clusters, write a prose section evaluating overall codebase quality, common themes across findings, and prioritized remediation recommendations.

### Findings File Template

Use this template for the findings file:

````markdown
# Code Quality Audit — [Title]

**Date:** YYYY-MM-DD
**Branch:** [branch name]
**Methodology:** Multi-pass convergence audit (batch pre-pass + agent passes)

## Severity Key
- **HIGH (H)** — Bugs, logic errors, race conditions, security issues
- **MEDIUM (M)** — Structural issues with contained scope
- **LOW (L)** — Minor issues, style concerns, small gaps
- **STYLE (S)** — Informational only

## Category Key
| Code | Category |
|------|----------|
| MT | Missing tests | UC | Unused code | TA | Type annotations |
| RC | Repeated code | UP | Unpythonic patterns | MC | Magic constants |
| HC | Hardcoded colors | PL | Print→Logging | IL | Incomplete logic |
| BL | Bugs/Logic errors | SM | Stale Makefile | LR | License registry |
| RL | Redundant license config |

---

## Pre-Pass — Automated Tools

| Tool | Issues | Notes |
|------|--------|-------|
| pyright | 0 | — |
| mypy | 0 | — |
| ruff check | 0 | — |
| ruff format | 0 | — |
| bandit | 0 | — |
| PyCharm | 0 | — |
| pytest | all pass | — |

---

## Findings

### HIGH — Bugs, logic errors, security issues

| ID | Cat | File | Lines | Finding | Pass |
|----|-----|------|-------|---------|------|
| H1 | BL  | `path/to/file.py` | 42–50 | **Description.** Details. | P1 |

### MEDIUM — Structural issues

| ID | Cat | File | Lines | Finding | Pass |
|----|-----|------|-------|---------|------|
| M1 | RC  | `path/to/file.py` | 10 | **Description.** Details. | P1 |

### LOW — Minor issues (grouped by theme)

| Theme | IDs | Count | Examples |
|-------|-----|-------|----------|
| Magic constants in GUI | L1, L4, L8 | 3 | `panel.py:42` hardcoded 600px width; `dialog.py:15` literal color |
| Missing type annotations | L2, L5 | 2 | `helper.py:10` missing return type; `utils.py:22` untyped param |

### STYLE — Informational only (grouped by theme)

| Theme | IDs | Count | Examples |
|-------|-----|-------|----------|
| Unpythonic patterns | S1, S3 | 2 | `foo.py:10` uses `len(x) == 0` instead of `not x` |

### Missing Tests

| ID | Source File | Gap | Pass |
|----|------------|-----|------|
| T1 | `path/to/file.py` | No tests for error paths in `method_name()` | P1 |

---

## Clusters

| # | Name | Findings | Root Cause | Fix | Priority |
|---|------|----------|------------|-----|----------|
| 1 | [Cluster name] | H1, M2, L5 | Shared root cause description | Suggested approach | High / Medium / Low |

---

## Assessment

### Overall Quality

Prose evaluation of the codebase's overall health — architecture, consistency, test coverage, error handling patterns, and how the findings compare to what you'd expect for a project of this size and maturity.

### Common Themes

Recurring patterns observed across multiple findings or clusters. These are systemic tendencies rather than isolated issues (e.g., "error paths are under-tested throughout", "magic constants concentrate in GUI code").

### Remediation Recommendations

Prioritized list of recommended actions, ordered by impact. Group by effort level (quick wins vs. larger refactors) and note which clusters each recommendation addresses.

---

## Rejected Findings

Findings that were raised in earlier passes but rejected during consolidation. Keep for transparency.

| ID | Cat | Finding | Reason Rejected | Pass |
|----|-----|---------|-----------------|------|
| ~A1~ | BL | **Description.** | Reason for rejection. | P1→P2 |

---

## Pass Log

| Pass     | Agents  | New Findings                   | Notes               |
|----------|---------|--------------------------------|----------------------|
| Pre-pass | (batch) | xH + xM + xL + xS = N         | Automated tools      |
| P1       | A, B, C, D | xH + xM + xL + xS = N      | Broad sweep          |
| P2       | E, F, G | xH + xM + xL + xS = N         | Deep dive, validations |
| P3       | H       | 0 new findings                 | **CONVERGED**        |

**Status: CONVERGED after N passes**
**Active totals: xH + xM + xL + xS = N findings across N clusters**
````

## How to Run

1. Create the output directory if needed (`mkdir -p _build/audit`)
2. Create a fresh findings file from the template above at `_build/audit/YYYYMMDDThhmm-code-quality.md`
3. Run the Pre-Pass: `make check`, PyCharm inspections, `pytest`, `make licenses-sync` — record results
4. Launch Pass 1: four parallel general-purpose agents (A, B, C, D) with the scopes defined above
5. Consolidate Pass 1 findings, cross-reference against pre-pass output
6. Launch Pass 2: two or three parallel agents (E, F, G) — pass them the Pass 1 findings for validation
7. Consolidate Pass 2 findings, apply confirmations/rejections
8. Launch Pass 3: one convergence agent sweeping uncovered areas
9. If zero new findings → converged. Otherwise, repeat.
10. Build clusters from the final findings set
11. Update the pass log and final totals

**No code changes during the audit** — the findings file is the deliverable.

## Coverage Analysis

When the audit identifies coverage gaps (MT/T findings) and remediation adds tests, follow the methodology in [`docs/coverage-analysis.md`](coverage-analysis.md) to document the work with a before/after comparison.
"""

QUALITY_AUDIT_AFTER = """\
# Code Quality Audit

When asked to audit the codebase, follow this methodology. The audit uses a batch pre-pass for automated tools, then parallel agents in convergence passes to systematically review every file.

## What to Look For

Check for these categories across all files in `app/`, `tests/`, and `scripts/`.

### Categories

| Code | Category                 | Description                                                                                                                                                                                          |
|------|--------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| MT   | Missing tests            | Public methods/functions without tests, untested error paths, shallow happy-path-only coverage                                                                                                       |
| UC   | Unused code              | Dead imports, unreachable code paths, unused functions/variables                                                                                                                                     |
| TA   | Type annotations         | Functions missing `-> None` or return types, untyped parameters                                                                                                                                      |
| RC   | Repeated code            | Duplicate logic across files that should be extracted to shared helpers                                                                                                                              |
| UP   | Unpythonic patterns      | `dict.__init__(self)` instead of `super().__init__()`, `lambda: Path()` instead of `Path`, `count == 0` instead of `not count`, etc.                                                                 |
| MC   | Magic constants          | Hardcoded strings, pixel values, colors, or numbers that should be named constants                                                                                                                   |
| HC   | Hardcoded colors         | `wx.Colour(...)` literals that duplicate values in `app/gui/styles.py`                                                                                                                               |
| PL   | Print instead of logging | `print()` calls that should use `logging.getLogger(__name__)`                                                                                                                                        |
| IL   | Incomplete logic         | Missing else branches, unhandled empty/None cases, no input validation                                                                                                                               |
| BL   | Bugs and logic errors    | Race conditions, off-by-one errors, unbounded loops, case-sensitivity mismatches, stale state after mutations, silent exception swallowing that hides real failures                                  |
| SM   | Stale Makefile           | Targets referencing outdated paths, wrong Python versions, missing new entry points, or commands that no longer match the project structure                                                          |
| LR   | License registry gaps    | Run `make licenses-sync`, then check `content/licenses/registry.toml` for: missing license text files, empty homepage URLs, "Unknown" license types, platform-specific packages for the exclude list |
| RL   | Redundant license config | `content/licenses/config.toml` `[[package]]` entries that only exist when they override auto-discovered values. Remove entries where `display` matches `name` and no other fields are set            |

### Severity Key

- **HIGH (H)** — Bugs, logic errors, race conditions, security issues — things that cause incorrect behavior
- **MEDIUM (M)** — Structural issues with contained scope — repeated code, incomplete logic, missing validation
- **LOW (L)** — Minor issues, style concerns, small gaps — magic constants, missing annotations, unpythonic patterns
- **STYLE (S)** — Informational only, not actionable defects

## Static Analysis

Run the full static analysis suite and verify zero issues across all tools:

```bash
make check   # runs all of the below in sequence
```

| Tool        | Command                                                   | Scope                                                 | Expected             |
|-------------|-----------------------------------------------------------|-------------------------------------------------------|----------------------|
| pyright     | `pyright app/ scripts/ main.py`                           | Type checking (structural)                            | 0 errors, 0 warnings |
| mypy        | `uv run mypy app/ scripts/ main.py`                       | Type checking (nominal, SQLAlchemy plugin)            | 0 errors             |
| ruff check  | `uv run ruff check app/ scripts/ tests/ main.py`          | Linting (pyflakes, pycodestyle, isort, bugbear, etc.) | 0 errors             |
| ruff format | `uv run ruff format --check app/ scripts/ tests/ main.py` | Formatting                                            | 0 reformatted        |
| bandit      | `uv run bandit -r app/ scripts/ -c pyproject.toml`        | Security scan                                         | 0 issues             |

For each diagnostic, determine whether to:
- **Fix the code** — if the checker found a real bug or a type that should be tightened
- **Add a suppression comment** (`# type: ignore[code]` or `# pyright: ignore[code]`) — if the diagnostic is a false positive or an intentional pattern (e.g. `sys._MEIPASS`, wxPython stubs)

**Before applying any suppression comments**, summarize every suppression to the user with:
1. The file, line, and diagnostic code
2. What the checker is complaining about
3. Why suppression (rather than a fix) is the right call

Wait for user approval before adding suppressions. The user may decide to fix the code, file an upstream bug, or handle it differently.

## PyCharm Inspections

Always attempt to run PyCharm inspections on all Python files in `main.py`, `app/**/*.py`, and `scripts/*.py` via the JetBrains MCP server. See the "PyCharm Inspections (MCP)" section in `CLAUDE.md` for details.

If the MCP server is unavailable (PyCharm not running, plugin not installed, tool calls fail), note the reason in the audit report and continue — do not fail the overall audit.

## Methodology: Multi-Pass Convergence

The audit runs in iterative passes. A batch pre-pass captures automated tool output, then parallel agents review the codebase from different angles. Passes continue until a pass produces zero new findings (**convergence**).

### Pre-Pass — Automated Baseline (batch, not agents)

Run these and capture output as reference material for agent passes:

1. `make check` — all static analysis diagnostics
2. PyCharm inspections — via JetBrains MCP on all Python files
3. `uv run pytest tests/ -x` — test results and coverage
4. `make licenses-sync` — license registry state

Tool-reported issues become pre-pass findings (category TA, UC, etc.) in the findings table. Agents in subsequent passes should not re-report what tools already caught.

### Pass 1 — Broad Sweep (4 parallel general-purpose agents)

| Agent | Scope                                        | Focus                                                         |
|-------|----------------------------------------------|---------------------------------------------------------------|
| A     | `app/core/**/*.py`                           | All 13 categories within core modules                         |
| B     | `app/gui/**/*.py`                            | All 13 categories within GUI modules                          |
| C     | `app/models/*.py`, `scripts/*.py`, `main.py` | All 13 categories within models, scripts, entry point         |
| D     | `tests/**/*.py`                              | Coverage gaps (compare test files against source modules), MT |

Each agent reads every file in its scope, checking:
1. **Import statements** — unused imports, circular dependencies
2. **Method bodies** — bugs, logic errors, race conditions, incomplete logic
3. **Type signatures** — missing annotations, loose types
4. **Constants and literals** — magic values, hardcoded colors
5. **Patterns** — unpythonic idioms, repeated code within scope
6. **Test coverage** — (Agent D) map source modules to test files, identify gaps

Each agent returns findings as a table with temporary IDs (A1, B1, C1, D1, ...).

### Interphase Consolidation Rules

After each pass:
1. **Deduplicate** — merge findings that describe the same issue from different agents
2. **Cross-reference pre-pass** — drop findings already reported by automated tools
3. **Adjust severity** — if a finding is confirmed with new context, upgrade or downgrade
4. **Strike rejected findings** — mark with ~~strikethrough~~ and note the rejection reason
5. **Assign final IDs** — sequential within severity (H1, M1, L1, S1)
6. **Update pass log** — record agent count, new findings, adjustments

### Pass 2 — Deep Dive + Validation (2–3 parallel agents)

| Agent | Focus                                                                                                                       |
|-------|-----------------------------------------------------------------------------------------------------------------------------|
| E     | **Cross-cutting**: repeated code across areas, inter-module coupling, shared pattern violations. Validates/rejects A, B, C. |
| F     | **Bugs + logic**: trace error flows, race conditions, edge cases adjacent to Pass 1 hits. Validates/rejects BL/IL findings. |
| G     | **Test coverage** (if D found gaps): map untested paths discovered by E and F. Validates/rejects D's findings. Optional.    |

Pass 2 agents receive the Pass 1 findings list. For each, they state **CONFIRMED** or **REJECTED** with reasoning. They also look for new findings in areas adjacent to Pass 1 hits.

### Pass 3+ — Convergence (1 agent)

One agent sweeps areas not specifically covered or lightly touched in prior passes:
- Makefile targets and project configuration (SM)
- License registry and config (LR, RL)
- Infrastructure files not in agent scopes
- Inter-module patterns missed by area-scoped agents
- Dead code across module boundaries

If this pass finds zero new findings, the audit is **converged**. Otherwise, repeat with targeted agents until convergence.

## Output

All findings go into `_build/audit/YYYYMMDDThhmm-code-quality.md` (timestamp of when the audit started). After convergence, group related findings into **clusters** — sets of findings that share a root cause or would be fixed together.

### Presentation Guidelines

- **HIGH and MEDIUM findings**: List individually in full detail tables (one row per finding). These are significant enough to warrant individual attention.
- **LOW findings**: Group by theme in a summary table. Each row is a theme (e.g., "Magic constants in GUI", "Missing type annotations in scripts") with a count and representative examples — not one row per finding.
- **STYLE findings**: Group by theme, same as LOW.
- **Missing Tests**: Separate table listing coverage gaps.
- **Clusters**: Present as a single table, not prose sections. Each row is a cluster with columns for name, included findings, root cause, fix approach, and priority.
- **Assessment**: After findings and clusters, write a prose section evaluating overall codebase quality, common themes across findings, and prioritized remediation recommendations.

### Findings File Template

Use this template for the findings file:

````markdown
# Code Quality Audit — [Title]

**Date:** YYYY-MM-DD
**Branch:** [branch name]
**Methodology:** Multi-pass convergence audit (batch pre-pass + agent passes)

## Severity Key
- **HIGH (H)** — Bugs, logic errors, race conditions, security issues
- **MEDIUM (M)** — Structural issues with contained scope
- **LOW (L)** — Minor issues, style concerns, small gaps
- **STYLE (S)** — Informational only

## Category Key
| Code | Category |
|------|----------|
| MT | Missing tests | UC | Unused code | TA | Type annotations |
| RC | Repeated code | UP | Unpythonic patterns | MC | Magic constants |
| HC | Hardcoded colors | PL | Print→Logging | IL | Incomplete logic |
| BL | Bugs/Logic errors | SM | Stale Makefile | LR | License registry |
| RL | Redundant license config |

---

## Pre-Pass — Automated Tools

| Tool | Issues | Notes |
|------|--------|-------|
| pyright | 0 | — |
| mypy | 0 | — |
| ruff check | 0 | — |
| ruff format | 0 | — |
| bandit | 0 | — |
| PyCharm | 0 | — |
| pytest | all pass | — |

---

## Findings

### HIGH — Bugs, logic errors, security issues

| ID | Cat | File | Lines | Finding | Pass |
|----|-----|------|-------|---------|------|
| H1 | BL  | `path/to/file.py` | 42–50 | **Description.** Details. | P1 |

### MEDIUM — Structural issues

| ID | Cat | File | Lines | Finding | Pass |
|----|-----|------|-------|---------|------|
| M1 | RC  | `path/to/file.py` | 10 | **Description.** Details. | P1 |

### LOW — Minor issues (grouped by theme)

| Theme | IDs | Count | Examples |
|-------|-----|-------|----------|
| Magic constants in GUI | L1, L4, L8 | 3 | `panel.py:42` hardcoded 600px width; `dialog.py:15` literal color |
| Missing type annotations | L2, L5 | 2 | `helper.py:10` missing return type; `utils.py:22` untyped param |

### STYLE — Informational only (grouped by theme)

| Theme | IDs | Count | Examples |
|-------|-----|-------|----------|
| Unpythonic patterns | S1, S3 | 2 | `foo.py:10` uses `len(x) == 0` instead of `not x` |

### Missing Tests

| ID | Source File | Gap | Pass |
|----|------------|-----|------|
| T1 | `path/to/file.py` | No tests for error paths in `method_name()` | P1 |

---

## Clusters

| # | Name | Findings | Root Cause | Fix | Priority |
|---|------|----------|------------|-----|----------|
| 1 | [Cluster name] | H1, M2, L5 | Shared root cause description | Suggested approach | High / Medium / Low |

---

## Assessment

### Overall Quality

Prose evaluation of the codebase's overall health — architecture, consistency, test coverage, error handling patterns, and how the findings compare to what you'd expect for a project of this size and maturity.

### Common Themes

Recurring patterns observed across multiple findings or clusters. These are systemic tendencies rather than isolated issues (e.g., "error paths are under-tested throughout", "magic constants concentrate in GUI code").

### Remediation Recommendations

Prioritized list of recommended actions, ordered by impact. Group by effort level (quick wins vs. larger refactors) and note which clusters each recommendation addresses.

---

## Rejected Findings

Findings that were raised in earlier passes but rejected during consolidation. Keep for transparency.

| ID | Cat | Finding | Reason Rejected | Pass |
|----|-----|---------|-----------------|------|
| ~A1~ | BL | **Description.** | Reason for rejection. | P1→P2 |

---

## Pass Log

| Pass     | Agents  | New Findings                   | Notes               |
|----------|---------|--------------------------------|----------------------|
| Pre-pass | (batch) | xH + xM + xL + xS = N         | Automated tools      |
| P1       | A, B, C, D | xH + xM + xL + xS = N      | Broad sweep          |
| P2       | E, F, G | xH + xM + xL + xS = N         | Deep dive, validations |
| P3       | H       | 0 new findings                 | **CONVERGED**        |

**Status: CONVERGED after N passes**
**Active totals: xH + xM + xL + xS = N findings across N clusters**
````

## How to Run

1. Create the output directory if needed (`mkdir -p _build/audit`)
2. Create a fresh findings file from the template above at `_build/audit/YYYYMMDDThhmm-code-quality.md`
3. Run the Pre-Pass: `make check`, PyCharm inspections, `pytest`, `make licenses-sync` — record results
4. Launch Pass 1: four parallel general-purpose agents (A, B, C, D) with the scopes defined above
5. Consolidate Pass 1 findings, cross-reference against pre-pass output
6. Launch Pass 2: two or three parallel agents (E, F, G) — pass them the Pass 1 findings for validation
7. Consolidate Pass 2 findings, apply confirmations/rejections
8. Launch Pass 3: one convergence agent sweeping uncovered areas
9. If zero new findings → converged. Otherwise, repeat.
10. Build clusters from the final findings set
11. Update the pass log and final totals

**No code changes during the audit** — the findings file is the deliverable.

## Coverage Analysis

When the audit identifies coverage gaps (MT/T findings) and remediation adds tests, follow the methodology in [`docs/coverage-analysis.md`](coverage-analysis.md) to document the work with a before/after comparison.
"""

COVERAGE_ANALYSIS_BEFORE = """\
# Full Project Coverage Analysis

**Coverage run:** `_build/coverage/20260303T2109/`
**Current coverage:** 94.6% (7579/8008 lines)

The project has strong coverage across both layers: app/ at 96% and scripts/ at 89%. The existing omit config (benchmarks, profiling, visual test harness, dark mode cycler, dmgbuild settings, entry-point trampolines) is properly applied, so the 94.6% figure represents only trackable code.

The app layer is exceptionally well-covered — 57 of 73 files at 100%, with gaps only in GUI rendering code (painting, wx event dispatch) and macOS-specific IPC (Apple Events). The scripts layer has strong coverage overall, with one benchmark utility at 0% that should be excluded and a few files in the 70-89% range that have testable gaps.

---

## Coverage Landscape

Every file in the project, grouped by coverage tier.

### Tier: 100% Coverage

| File | Lines |
|---|---|
| `app/__init__.py` | 1 |
| `app/core/card_store.py` | 144 |
| `app/core/config.py` | 60 |
| `app/core/constants.py` | 8 |
| `app/core/content/changelog.py` | 112 |
| `app/core/content/changelog_models.py` | 6 |
| `app/core/content/help_builder.py` | 111 |
| `app/core/content/license_html.py` | 88 |
| `app/core/content/license_models.py` | 26 |
| `app/core/content/license_sync.py` | 218 |
| `app/core/content/template_env.py` | 10 |
| `app/core/database.py` | 368 |
| `app/core/logging_config.py` | 3 |
| `app/core/naming/extractor.py` | 90 |
| `app/core/naming/family_name/__init__.py` | 4 |
| `app/core/naming/family_name/cleaning.py` | 51 |
| `app/core/naming/family_name/data.py` | 101 |
| `app/core/naming/family_name/formatting.py` | 59 |
| `app/core/naming/filename_safety.py` | 5 |
| `app/core/naming/rename_filter.py` | 5 |
| `app/core/naming/renamer.py` | 101 |
| `app/core/paths.py` | 19 |
| `app/core/pipeline/ai_analyzer.py` | 97 |
| `app/core/pipeline/card_processor.py` | 53 |
| `app/core/pipeline/ocr_engine.py` | 26 |
| `app/core/pipeline/pdf_renderer.py` | 41 |
| `app/core/pipeline/pdf_worker.py` | 40 |
| `app/core/pipeline/rate_limit.py` | 11 |
| `app/core/platform.py` | 19 |
| `app/core/scripting_protocol.py` | 4 |
| `app/core/services/ai_service.py` | 12 |
| `app/core/services/card_service.py` | 111 |
| `app/core/services/config_service.py` | 33 |
| `app/core/services/filter_service.py` | 66 |
| `app/core/services/processing_service.py` | 56 |
| `app/core/services/rename_service.py` | 43 |
| `app/gui/components/filter_sidebar.py` | 214 |
| `app/gui/components/toolbar.py` | 169 |
| `app/gui/context_menu.py` | 31 |
| `app/gui/dialogs/__init__.py` | 1 |
| `app/gui/dialogs/api_key.py` | 10 |
| `app/gui/dialogs/changelog.py` | 8 |
| `app/gui/dialogs/common.py` | 247 |
| `app/gui/dialogs/help.py` | 8 |
| `app/gui/dialogs/licenses.py` | 8 |
| `app/gui/dialogs/settings.py` | 140 |
| `app/gui/main_window_mixins/__init__.py` | 5 |
| `app/gui/main_window_mixins/_protocol.py` | 33 |
| `app/gui/main_window_mixins/ai_mixin.py` | 115 |
| `app/gui/main_window_mixins/filter_mixin.py` | 45 |
| `app/gui/main_window_mixins/selection_mixin.py` | 54 |
| `app/gui/rename_display.py` | 38 |
| `app/gui/styles.py` | 90 |
| `app/models/card.py` | 118 |
| `scripts/build_family_name_db/_unicode.py` | 11 |
| `scripts/build_family_name_db/sources/census.py` | 41 |
| `scripts/build_family_name_db/sources/smashew.py` | 42 |
| `scripts/configure_release/cli.py` | 89 |
| `scripts/configure_release/keychain.py` | 15 |
| `scripts/configure_release/ui.py` | 35 |
| `scripts/dmg/cli.py` | 23 |
| `scripts/generate_diagnostic_cards/cli.py` | 54 |
| `scripts/generate_sample_cards/display.py` | 45 |
| `scripts/generate_sample_cards/models.py` | 41 |
| `scripts/generate_sample_cards/pdf_composer.py` | 19 |
| `scripts/generate_sample_cards/spec_generators/__init__.py` | 15 |
| `scripts/generate_sample_cards/spec_generators/color_schemes.py` | 23 |
| `scripts/generate_sample_cards/spec_generators/constants.py` | 12 |
| `scripts/generate_sample_cards/spec_generators/family_names.py` | 16 |
| `scripts/generate_sample_cards/spec_generators/formatting.py` | 42 |
| `scripts/generate_sample_cards/spec_generators/subtitles.py` | 24 |
| `scripts/helpers.py` | 33 |

**90 files, 4116 lines** at full coverage.

### Tier: 90-99% Coverage

| File | Coverage | Uncovered Lines |
|---|---|---|
| `scripts/release/cli.py` | 91% (75/82) | 7 |
| `scripts/generate_sample_cards/image_generator.py` | 92% (97/106) | 9 |
| `scripts/notarize/cli.py` | 92% (47/51) | 4 |
| `app/core/pipeline/ai_batch.py` | 93% (75/81) | 6 |
| `scripts/build_family_name_db/sources/faker_names.py` | 93% (41/44) | 3 |
| `scripts/generate_sample_cards/cli.py` | 94% (110/117) | 7 |
| `app/gui/appearance.py` | 95% (37/39) | 2 |
| `scripts/generate_sample_cards/spec_generators/utils.py` | 96% (49/51) | 2 |
| `app/gui/components/review_panel.py` | 96% (617/640) | 23 |
| `app/gui/icons.py` | 97% (90/93) | 3 |
| `scripts/sign/cli.py` | 97% (63/65) | 2 |
| `app/gui/components/html_viewer.py` | 97% (384/396) | 12 |
| `scripts/build_family_name_db/cli.py` | 98% (44/45) | 1 |
| `scripts/generate_sample_cards/spec_generators/card_content.py` | 98% (45/46) | 1 |
| `app/gui/main_window.py` | 98% (380/387) | 7 |
| `scripts/generate_sample_cards/spec_generator.py` | 98% (58/59) | 1 |
| `scripts/configure_release/generator.py` | 98% (118/120) | 2 |
| `scripts/dmg/readme.py` | 99% (72/73) | 1 |
| `app/gui/main_window_mixins/apple_events_mixin.py` | 99% (109/110) | 1 |

**19 files, 93 uncovered lines.** Most are near their testability ceiling — remaining gaps are GUI rendering paths, subprocess wrappers, and rare edge cases.

### Tier: 70-89% Coverage

| File | Coverage | Uncovered Lines | Notes |
|---|---|---|---|
| `scripts/run_tests.py` | 73% (112/154) | 42 | Coverage post-processing: `_generate_lcov()`, `_generate_grouped_html()`, symlink management |
| `scripts/reformat_md_tables.py` | 83% (62/75) | 13 | Edge cases: code block detection, malformed table rows, `main()` error handling |
| `app/gui/utils.py` | 85% (35/41) | 6 | NSOpenPanel native dialog, PIL color mode conversion branches |
| `scripts/build_family_name_db/merger.py` | 89% (138/155) | 17 | Error handling in `_sanity_check()`, override file edge cases |
| `app/gui/components/preview_panel.py` | 89% (297/333) | 36 | `_on_paint()`, cursor/timer management, `_paint_error()` rendering |

### Tier: Below 70%

| File | Coverage | Uncovered Lines | Notes |
|---|---|---|---|
| `scripts/build_family_name_db/benchmark_compression.py` | 0% (0/77) | 77 | Compression format benchmark; requires real TSV data, no testable logic |
| `app/gui/components/drop_target.py` | 65% (72/111) | 39 | `DropOverlay._on_paint()`, `_scale_bg()`, wx event handlers |
| `scripts/dmg/background.py` | 69% (48/70) | 22 | `_sf_chevron()` AppKit SF Symbol rendering (macOS-only) |
| `app/core/apple_events.py` | 69% (188/271) | 83 | 15 Apple Event handler methods + parameter extraction helpers |

---

## Gap Analysis

### Proposed Exclusions

One file should be added to `[tool.coverage.run] omit`:

```toml
[tool.coverage.run]
omit = [
    # (existing entries...)
    # Compression format benchmark — requires real TSV data, tests would be meaningless
    "scripts/build_family_name_db/benchmark_compression.py",
]
```

**Lines removed from tracking:** ~77

### Targeted Tests

#### `app/core/apple_events.py` (69% -> ~78%)

| Test | What It Covers |
|---|---|
| `test_get_text_param` | `_get_text_param()` extracting string from NSAppleEventDescriptor |
| `test_get_int_param` | `_get_int_param()` extracting integer from descriptor |
| `test_set_text_reply` | `_set_text_reply()` setting reply descriptor |
| `test_card_to_json` | `_card_to_json()` serialization of card data |
| `test_ae_handler_open_folder` | `handleLoadPaths_` dispatching to main thread |
| `test_ae_handler_get_status` | `handleGetStatus_` returning idle/processing state |
| `test_ae_handler_list_cards` | `handleListCards_` JSON serialization of card list |

**Mocking:** `_call_on_main_thread` to execute callbacks synchronously; mock `NSAppleEventDescriptor` for parameter extraction. AE registration and threading infrastructure are untestable (macOS runtime only) — ceiling is ~80%.

#### `app/gui/components/drop_target.py` (65% -> ~75%)

| Test | What It Covers |
|---|---|
| `test_scale_bg_caching` | `_scale_bg()` background scaling and cache logic |
| `test_drop_overlay_show_hide` | `DropOverlay.show()` / `hide()` state transitions |
| `test_file_drop_target_valid_pdfs` | `OnDropFiles` accepting PDF files |
| `test_file_drop_target_filtering` | `OnDropFiles` rejecting non-PDF files |
| `test_load_drop_background_error` | `load_drop_background()` exception handling path |

**Mocking:** `wx.FileDropTarget` callbacks, `wx.Panel` for overlay. `_on_paint()` rendering requires Display — untestable ceiling.

#### `scripts/run_tests.py` (73% -> ~85%)

| Test | What It Covers |
|---|---|
| `test_generate_lcov` | `_generate_lcov()` subprocess call construction |
| `test_generate_grouped_html_available` | `_generate_grouped_html()` when genhtml is available |
| `test_generate_grouped_html_missing` | `_generate_grouped_html()` when genhtml not on PATH |
| `test_update_latest_symlink` | `_update_latest_symlink()` creating/updating symlinks |
| `test_open_report` | `_open_report()` path construction and browser launch |

**Mocking:** `subprocess.run`, `shutil.which`, `webbrowser.open`, `Path.symlink_to()`. Pure orchestration — straightforward to mock.

#### `scripts/reformat_md_tables.py` (83% -> ~93%)

| Test | What It Covers |
|---|---|
| `test_code_block_detection` | `process_file()` skipping tables inside fenced code blocks |
| `test_malformed_table_rows` | `_reformat_table()` handling rows with wrong column count |
| `test_main_error_handling` | `main()` handling write failures gracefully |

**Mocking:** File I/O via temp files. All functions are pure string/list manipulation — easy to test.

#### `scripts/build_family_name_db/merger.py` (89% -> ~95%)

| Test | What It Covers |
|---|---|
| `test_sanity_check_error_reporting` | `_sanity_check()` error branches for missing/malformed data |
| `test_apply_overrides_edge_cases` | `apply_overrides()` with empty files, malformed rows, alternates parsing |

**Mocking:** None needed — pure dict/list manipulation. Use simple fixture data.

#### `app/gui/components/preview_panel.py` (89% -> ~93%)

| Test | What It Covers |
|---|---|
| `test_paint_error_fallback` | `_paint_error()` rendering error message when PDF fails |
| `test_cursor_loading_fallback` | Cursor initialization when `load_cursor_from_symbol()` fails |
| `test_wrap_text_edge_cases` | `_wrap_text()` with very long words, empty strings |

**Mocking:** `wx.PaintDC`, `wx.GraphicsContext` for paint tests. Cursor loading requires mocking `load_cursor_from_symbol` to raise.

#### `scripts/dmg/background.py` (69% -> ~74%)

| Test | What It Covers |
|---|---|
| `test_generate_creates_files` | `generate()` producing 1x and 2x images in temp dir |

**Mocking:** `_sf_chevron()` must be mocked (requires AppKit). PIL gradient operations are testable directly. Ceiling is ~75% due to AppKit dependency.

---

## Summary

| Part | Tests Added | Coverage Impact |
|---|---|---|
| Exclusion config | 0 | Removes ~77 untestable lines from denominator |
| `app/core/apple_events.py` | 7 | 69% -> ~78% |
| `app/gui/components/drop_target.py` | 5 | 65% -> ~75% |
| `scripts/run_tests.py` | 5 | 73% -> ~85% |
| `scripts/reformat_md_tables.py` | 3 | 83% -> ~93% |
| `scripts/build_family_name_db/merger.py` | 2 | 89% -> ~95% |
| `app/gui/components/preview_panel.py` | 3 | 89% -> ~93% |
| `scripts/dmg/background.py` | 1 | 69% -> ~74% |
| **Total** | **~26 tests** | Project coverage: 94.6% -> **~96.5%** |

The project is in excellent shape at 94.6%. The proposed work targets the most impactful gaps — Apple Events handlers (83 uncovered lines), test runner post-processing (42 lines), and drag-and-drop (39 lines) — for an estimated 2pp improvement to ~96.5%. Beyond this, diminishing returns set in: remaining uncovered lines are GUI painting, macOS-native rendering, and rarely-hit error paths.

---

## Verification

1. `make check` — all static checks pass
2. `uv run pytest tests/ -x` — all tests pass (existing + new)
3. `make test T="default --cov"` — rerun coverage and verify:
   - `scripts/build_family_name_db/benchmark_compression.py` no longer appears in coverage report
   - Coverage percentage reflects the new baseline
"""

COVERAGE_ANALYSIS_AFTER = """\
# Full Project Coverage Analysis

**Coverage run:** `_build/coverage/20260303T2109/`
**Current coverage:** 94.6% (7579/8008 lines)

The project has strong coverage across both layers: app/ at 96% and scripts/ at 89%. The existing omit config (benchmarks, profiling, visual test harness, dark mode cycler, dmgbuild settings, entry-point trampolines) is properly applied, so the 94.6% figure represents only trackable code.

The app layer is exceptionally well-covered — 57 of 73 files at 100%, with gaps only in GUI rendering code (painting, wx event dispatch) and macOS-specific IPC (Apple Events). The scripts layer has strong coverage overall, with one benchmark utility at 0% that should be excluded and a few files in the 70-89% range that have testable gaps.

---

## Coverage Landscape

Every file in the project, grouped by coverage tier.

### Tier: 100% Coverage

| File                                                             | Lines |
|------------------------------------------------------------------|-------|
| `app/__init__.py`                                                | 1     |
| `app/core/card_store.py`                                         | 144   |
| `app/core/config.py`                                             | 60    |
| `app/core/constants.py`                                          | 8     |
| `app/core/content/changelog.py`                                  | 112   |
| `app/core/content/changelog_models.py`                           | 6     |
| `app/core/content/help_builder.py`                               | 111   |
| `app/core/content/license_html.py`                               | 88    |
| `app/core/content/license_models.py`                             | 26    |
| `app/core/content/license_sync.py`                               | 218   |
| `app/core/content/template_env.py`                               | 10    |
| `app/core/database.py`                                           | 368   |
| `app/core/logging_config.py`                                     | 3     |
| `app/core/naming/extractor.py`                                   | 90    |
| `app/core/naming/family_name/__init__.py`                        | 4     |
| `app/core/naming/family_name/cleaning.py`                        | 51    |
| `app/core/naming/family_name/data.py`                            | 101   |
| `app/core/naming/family_name/formatting.py`                      | 59    |
| `app/core/naming/filename_safety.py`                             | 5     |
| `app/core/naming/rename_filter.py`                               | 5     |
| `app/core/naming/renamer.py`                                     | 101   |
| `app/core/paths.py`                                              | 19    |
| `app/core/pipeline/ai_analyzer.py`                               | 97    |
| `app/core/pipeline/card_processor.py`                            | 53    |
| `app/core/pipeline/ocr_engine.py`                                | 26    |
| `app/core/pipeline/pdf_renderer.py`                              | 41    |
| `app/core/pipeline/pdf_worker.py`                                | 40    |
| `app/core/pipeline/rate_limit.py`                                | 11    |
| `app/core/platform.py`                                           | 19    |
| `app/core/scripting_protocol.py`                                 | 4     |
| `app/core/services/ai_service.py`                                | 12    |
| `app/core/services/card_service.py`                              | 111   |
| `app/core/services/config_service.py`                            | 33    |
| `app/core/services/filter_service.py`                            | 66    |
| `app/core/services/processing_service.py`                        | 56    |
| `app/core/services/rename_service.py`                            | 43    |
| `app/gui/components/filter_sidebar.py`                           | 214   |
| `app/gui/components/toolbar.py`                                  | 169   |
| `app/gui/context_menu.py`                                        | 31    |
| `app/gui/dialogs/__init__.py`                                    | 1     |
| `app/gui/dialogs/api_key.py`                                     | 10    |
| `app/gui/dialogs/changelog.py`                                   | 8     |
| `app/gui/dialogs/common.py`                                      | 247   |
| `app/gui/dialogs/help.py`                                        | 8     |
| `app/gui/dialogs/licenses.py`                                    | 8     |
| `app/gui/dialogs/settings.py`                                    | 140   |
| `app/gui/main_window_mixins/__init__.py`                         | 5     |
| `app/gui/main_window_mixins/_protocol.py`                        | 33    |
| `app/gui/main_window_mixins/ai_mixin.py`                         | 115   |
| `app/gui/main_window_mixins/filter_mixin.py`                     | 45    |
| `app/gui/main_window_mixins/selection_mixin.py`                  | 54    |
| `app/gui/rename_display.py`                                      | 38    |
| `app/gui/styles.py`                                              | 90    |
| `app/models/card.py`                                             | 118   |
| `scripts/build_family_name_db/_unicode.py`                       | 11    |
| `scripts/build_family_name_db/sources/census.py`                 | 41    |
| `scripts/build_family_name_db/sources/smashew.py`                | 42    |
| `scripts/configure_release/cli.py`                               | 89    |
| `scripts/configure_release/keychain.py`                          | 15    |
| `scripts/configure_release/ui.py`                                | 35    |
| `scripts/dmg/cli.py`                                             | 23    |
| `scripts/generate_diagnostic_cards/cli.py`                       | 54    |
| `scripts/generate_sample_cards/display.py`                       | 45    |
| `scripts/generate_sample_cards/models.py`                        | 41    |
| `scripts/generate_sample_cards/pdf_composer.py`                  | 19    |
| `scripts/generate_sample_cards/spec_generators/__init__.py`      | 15    |
| `scripts/generate_sample_cards/spec_generators/color_schemes.py` | 23    |
| `scripts/generate_sample_cards/spec_generators/constants.py`     | 12    |
| `scripts/generate_sample_cards/spec_generators/family_names.py`  | 16    |
| `scripts/generate_sample_cards/spec_generators/formatting.py`    | 42    |
| `scripts/generate_sample_cards/spec_generators/subtitles.py`     | 24    |
| `scripts/helpers.py`                                             | 33    |

**90 files, 4116 lines** at full coverage.

### Tier: 90-99% Coverage

| File                                                            | Coverage      | Uncovered Lines |
|-----------------------------------------------------------------|---------------|-----------------|
| `scripts/release/cli.py`                                        | 91% (75/82)   | 7               |
| `scripts/generate_sample_cards/image_generator.py`              | 92% (97/106)  | 9               |
| `scripts/notarize/cli.py`                                       | 92% (47/51)   | 4               |
| `app/core/pipeline/ai_batch.py`                                 | 93% (75/81)   | 6               |
| `scripts/build_family_name_db/sources/faker_names.py`           | 93% (41/44)   | 3               |
| `scripts/generate_sample_cards/cli.py`                          | 94% (110/117) | 7               |
| `app/gui/appearance.py`                                         | 95% (37/39)   | 2               |
| `scripts/generate_sample_cards/spec_generators/utils.py`        | 96% (49/51)   | 2               |
| `app/gui/components/review_panel.py`                            | 96% (617/640) | 23              |
| `app/gui/icons.py`                                              | 97% (90/93)   | 3               |
| `scripts/sign/cli.py`                                           | 97% (63/65)   | 2               |
| `app/gui/components/html_viewer.py`                             | 97% (384/396) | 12              |
| `scripts/build_family_name_db/cli.py`                           | 98% (44/45)   | 1               |
| `scripts/generate_sample_cards/spec_generators/card_content.py` | 98% (45/46)   | 1               |
| `app/gui/main_window.py`                                        | 98% (380/387) | 7               |
| `scripts/generate_sample_cards/spec_generator.py`               | 98% (58/59)   | 1               |
| `scripts/configure_release/generator.py`                        | 98% (118/120) | 2               |
| `scripts/dmg/readme.py`                                         | 99% (72/73)   | 1               |
| `app/gui/main_window_mixins/apple_events_mixin.py`              | 99% (109/110) | 1               |

**19 files, 93 uncovered lines.** Most are near their testability ceiling — remaining gaps are GUI rendering paths, subprocess wrappers, and rare edge cases.

### Tier: 70-89% Coverage

| File                                     | Coverage      | Uncovered Lines | Notes                                                                                        |
|------------------------------------------|---------------|-----------------|----------------------------------------------------------------------------------------------|
| `scripts/run_tests.py`                   | 73% (112/154) | 42              | Coverage post-processing: `_generate_lcov()`, `_generate_grouped_html()`, symlink management |
| `scripts/reformat_md_tables.py`          | 83% (62/75)   | 13              | Edge cases: code block detection, malformed table rows, `main()` error handling              |
| `app/gui/utils.py`                       | 85% (35/41)   | 6               | NSOpenPanel native dialog, PIL color mode conversion branches                                |
| `scripts/build_family_name_db/merger.py` | 89% (138/155) | 17              | Error handling in `_sanity_check()`, override file edge cases                                |
| `app/gui/components/preview_panel.py`    | 89% (297/333) | 36              | `_on_paint()`, cursor/timer management, `_paint_error()` rendering                           |

### Tier: Below 70%

| File                                                    | Coverage      | Uncovered Lines | Notes                                                                   |
|---------------------------------------------------------|---------------|-----------------|-------------------------------------------------------------------------|
| `scripts/build_family_name_db/benchmark_compression.py` | 0% (0/77)     | 77              | Compression format benchmark; requires real TSV data, no testable logic |
| `app/gui/components/drop_target.py`                     | 65% (72/111)  | 39              | `DropOverlay._on_paint()`, `_scale_bg()`, wx event handlers             |
| `scripts/dmg/background.py`                             | 69% (48/70)   | 22              | `_sf_chevron()` AppKit SF Symbol rendering (macOS-only)                 |
| `app/core/apple_events.py`                              | 69% (188/271) | 83              | 15 Apple Event handler methods + parameter extraction helpers           |

---

## Gap Analysis

### Proposed Exclusions

One file should be added to `[tool.coverage.run] omit`:

```toml
[tool.coverage.run]
omit = [
    # (existing entries...)
    # Compression format benchmark — requires real TSV data, tests would be meaningless
    "scripts/build_family_name_db/benchmark_compression.py",
]
```

**Lines removed from tracking:** ~77

### Targeted Tests

#### `app/core/apple_events.py` (69% -> ~78%)

| Test                          | What It Covers                                                    |
|-------------------------------|-------------------------------------------------------------------|
| `test_get_text_param`         | `_get_text_param()` extracting string from NSAppleEventDescriptor |
| `test_get_int_param`          | `_get_int_param()` extracting integer from descriptor             |
| `test_set_text_reply`         | `_set_text_reply()` setting reply descriptor                      |
| `test_card_to_json`           | `_card_to_json()` serialization of card data                      |
| `test_ae_handler_open_folder` | `handleLoadPaths_` dispatching to main thread                     |
| `test_ae_handler_get_status`  | `handleGetStatus_` returning idle/processing state                |
| `test_ae_handler_list_cards`  | `handleListCards_` JSON serialization of card list                |

**Mocking:** `_call_on_main_thread` to execute callbacks synchronously; mock `NSAppleEventDescriptor` for parameter extraction. AE registration and threading infrastructure are untestable (macOS runtime only) — ceiling is ~80%.

#### `app/gui/components/drop_target.py` (65% -> ~75%)

| Test                               | What It Covers                                    |
|------------------------------------|---------------------------------------------------|
| `test_scale_bg_caching`            | `_scale_bg()` background scaling and cache logic  |
| `test_drop_overlay_show_hide`      | `DropOverlay.show()` / `hide()` state transitions |
| `test_file_drop_target_valid_pdfs` | `OnDropFiles` accepting PDF files                 |
| `test_file_drop_target_filtering`  | `OnDropFiles` rejecting non-PDF files             |
| `test_load_drop_background_error`  | `load_drop_background()` exception handling path  |

**Mocking:** `wx.FileDropTarget` callbacks, `wx.Panel` for overlay. `_on_paint()` rendering requires Display — untestable ceiling.

#### `scripts/run_tests.py` (73% -> ~85%)

| Test                                   | What It Covers                                        |
|----------------------------------------|-------------------------------------------------------|
| `test_generate_lcov`                   | `_generate_lcov()` subprocess call construction       |
| `test_generate_grouped_html_available` | `_generate_grouped_html()` when genhtml is available  |
| `test_generate_grouped_html_missing`   | `_generate_grouped_html()` when genhtml not on PATH   |
| `test_update_latest_symlink`           | `_update_latest_symlink()` creating/updating symlinks |
| `test_open_report`                     | `_open_report()` path construction and browser launch |

**Mocking:** `subprocess.run`, `shutil.which`, `webbrowser.open`, `Path.symlink_to()`. Pure orchestration — straightforward to mock.

#### `scripts/reformat_md_tables.py` (83% -> ~93%)

| Test                        | What It Covers                                             |
|-----------------------------|------------------------------------------------------------|
| `test_code_block_detection` | `process_file()` skipping tables inside fenced code blocks |
| `test_malformed_table_rows` | `_reformat_table()` handling rows with wrong column count  |
| `test_main_error_handling`  | `main()` handling write failures gracefully                |

**Mocking:** File I/O via temp files. All functions are pure string/list manipulation — easy to test.

#### `scripts/build_family_name_db/merger.py` (89% -> ~95%)

| Test                                | What It Covers                                                           |
|-------------------------------------|--------------------------------------------------------------------------|
| `test_sanity_check_error_reporting` | `_sanity_check()` error branches for missing/malformed data              |
| `test_apply_overrides_edge_cases`   | `apply_overrides()` with empty files, malformed rows, alternates parsing |

**Mocking:** None needed — pure dict/list manipulation. Use simple fixture data.

#### `app/gui/components/preview_panel.py` (89% -> ~93%)

| Test                           | What It Covers                                               |
|--------------------------------|--------------------------------------------------------------|
| `test_paint_error_fallback`    | `_paint_error()` rendering error message when PDF fails      |
| `test_cursor_loading_fallback` | Cursor initialization when `load_cursor_from_symbol()` fails |
| `test_wrap_text_edge_cases`    | `_wrap_text()` with very long words, empty strings           |

**Mocking:** `wx.PaintDC`, `wx.GraphicsContext` for paint tests. Cursor loading requires mocking `load_cursor_from_symbol` to raise.

#### `scripts/dmg/background.py` (69% -> ~74%)

| Test                          | What It Covers                                      |
|-------------------------------|-----------------------------------------------------|
| `test_generate_creates_files` | `generate()` producing 1x and 2x images in temp dir |

**Mocking:** `_sf_chevron()` must be mocked (requires AppKit). PIL gradient operations are testable directly. Ceiling is ~75% due to AppKit dependency.

---

## Summary

| Part                                     | Tests Added   | Coverage Impact                               |
|------------------------------------------|---------------|-----------------------------------------------|
| Exclusion config                         | 0             | Removes ~77 untestable lines from denominator |
| `app/core/apple_events.py`               | 7             | 69% -> ~78%                                   |
| `app/gui/components/drop_target.py`      | 5             | 65% -> ~75%                                   |
| `scripts/run_tests.py`                   | 5             | 73% -> ~85%                                   |
| `scripts/reformat_md_tables.py`          | 3             | 83% -> ~93%                                   |
| `scripts/build_family_name_db/merger.py` | 2             | 89% -> ~95%                                   |
| `app/gui/components/preview_panel.py`    | 3             | 89% -> ~93%                                   |
| `scripts/dmg/background.py`              | 1             | 69% -> ~74%                                   |
| **Total**                                | **~26 tests** | Project coverage: 94.6% -> **~96.5%**         |

The project is in excellent shape at 94.6%. The proposed work targets the most impactful gaps — Apple Events handlers (83 uncovered lines), test runner post-processing (42 lines), and drag-and-drop (39 lines) — for an estimated 2pp improvement to ~96.5%. Beyond this, diminishing returns set in: remaining uncovered lines are GUI painting, macOS-native rendering, and rarely-hit error paths.

---

## Verification

1. `make check` — all static checks pass
2. `uv run pytest tests/ -x` — all tests pass (existing + new)
3. `make test T="default --cov"` — rerun coverage and verify:
   - `scripts/build_family_name_db/benchmark_compression.py` no longer appears in coverage report
   - Coverage percentage reflects the new baseline
"""
