"""ScriptingTarget — structural type for the Apple Events handler target.

Defines the interface that ``AppleEventHandler`` calls on the window
object, so the core layer never imports from the GUI layer.
"""

from __future__ import annotations

from typing import Protocol

from app.models.card import CardResult


class ScriptingTarget(Protocol):
    """All methods + properties the AppleEventHandler calls on MainWindow."""

    @property
    def is_processing(self) -> bool: ...

    @property
    def is_ai_running(self) -> bool: ...

    def get_status_for_script(self) -> dict: ...

    def get_card_info_for_script(self, filename: str) -> CardResult | None: ...

    def get_all_cards_for_script(self) -> list[CardResult]: ...

    def load_paths_for_script(self, paths: list[str]) -> dict: ...

    def rename_card_for_script(self, filename: str, new_name: str, year: str | None) -> dict: ...

    def set_card_name_for_script(self, filename: str, name: str) -> dict: ...

    def select_candidate_for_script(self, filename: str, rank: int) -> dict: ...

    def set_remove_family_for_script(self, filename: str, value: bool) -> dict: ...

    def analyze_for_script(self, filename: str | None) -> dict: ...

    def clear_ai_for_script(self, filename: str | None) -> dict: ...

    def reload_for_script(self) -> dict: ...

    def clear_all_for_script(self) -> dict: ...

    def set_ai_model_for_script(self, model_id: str) -> dict: ...

    def quit_for_script(self) -> None: ...
